add flag --show-old to only charts not on the latest version
FairwindsOps/nova pull request #111
Opened 2022-05-20 18:00 UTC by MarkAndersonTrocme

This PR fixes #110 

## Checklist
* [ ] I have signed the CLA
* [x] I have updated/added any relevant documentation

## Description
### What's the goal of this PR?
Add a flag `--show-old` to only output charts that are not on the latest version. 

### What changes did you make?
Added a flag `--show-old` which hides the output if chart is not old

### What alternative solution should we consider, if any?
none

2022-05-20 18:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FairwindsOps/nova?pullRequest=111) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/FairwindsOps/nova?pullRequest=111) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/FairwindsOps/nova?pullRequest=111) it.</sub>

2022-06-03 14:13 UTC, sudermanjr commented on cmd/root.go
> +		klog.Fatalf("Failed to bind show-old flag: %v", err)
Fatal has started spewing stack traces, so we're moving to Exitf everywhere. 

```suggestion
		klog.Exitf("Failed to bind show-old flag: %v", err)
```

2022-06-03 14:16 UTC, rbren approved these changes

2022-06-03 14:21 UTC, sudermanjr requested changes
(inline comment)

2022-06-03 14:22 UTC, sudermanjr approved these changes

2022-06-03 14:22 UTC, merged